repos:
  - repo: https://github.com/cachedjdk/cjdk-pre-commit
    rev: v0.1.0
    hooks:
      - id: checkstyle
        args:
          - --jdk=temurin-jre:17
          - --tool-version=10.3.1
          - --jvm-arg=-Dcheckstyle.javadoc.severity=ignore
          - --
          - -c
          - buildscripts/codestyle/checkstyle.xml
        files: '^(mmstudio/src/main/java/|libraries|plugins/Duplicator|plugins/MMClearVolumePlugin|plugins/Magellan|plugins/SharpnessInspector|plugins/ZProjector)'
        exclude: '^(libraries/Gaussian/src/main/java/edu/ucsf/valelab/tsf)'
